"""testing3

Revision ID: 68be22beef67
Revises: 9fa273b9c6cd
Create Date: 2025-03-20 16:41:27.671447

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '68be22beef67'
down_revision: Union[str, None] = '9fa273b9c6cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('experience', sa.Integer(), server_default='1', nullable=False))
    op.drop_column('users', 'level')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('level', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
    op.drop_column('users', 'experience')
    # ### end Alembic commands ###
