"""new user

Revision ID: 9b395c7b00ed
Revises: fc3415223fdd
Create Date: 2025-03-24 19:30:04.232997

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b395c7b00ed'
down_revision: Union[str, None] = 'fc3415223fdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True))
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('users', 'avatar_url')
    # ### end Alembic commands ###
